apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    apps: node-app
spec:
  selector:
    matchLabels:
      apps: node-app
  replicas: 4
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        apps: node-app
    spec:
       containers:
        -  name: node-app
           image: shwetakuthi90/node-image:1
           ports:
            - name: http
              containerPort: 3010
              protocol: TCP
           resources:
            requests:
              memory: 250Mi
              cpu: 250m
            limits:
              memory: 250Mi
              cpu: 500m

        
